globalweb = {
    'zh_CN': {
        'title': '综合主机状态监控大屏',
        'search': '搜索主机名或IP...',
        'online': '在线',
        'offline': '离线',
        'warming': '警告',
        'error': '故障',
        'host_status': '主机状态监控',
        'refresh': '刷新',
        'add' : '添加',
        'logout' : '登出',
        'cpu_status': 'CPU利用率',
        'service_status': '服务状态',
        'memory_status' : '内存使用',
        'data_status' : '网络流量',
        'memory' : '内存',
        'storage' : '磁盘',
        'contributors' : '贡献者',
        'ip': 'IP 地址',
        'GitHub_Repository' : 'GitHub 仓库',
        'hostname' : '主机名',
        'username' : '用户名',
        'groupname' : '群组名',
        'password': '密码',
        'port' : '端口',
        'edit' : '编辑',
        'delete' : '删除',
        'edit_message' : '将编辑主机',
        'save' : '保存',
        'input' : '入口流量',
        'output' : '出口流量',
        'deletc' : '已删除',
        'delete_fail' : '删除失败',
        'confirm_delete_host': '确定要删除主机 ID: {host_id} 吗？',
        'edit_success' : '编辑成功',
        'edit_fail' : '编辑失败',
        'check_network' : '请求失败，请检查网络',
        'checkip' : 'IP 地址 {inputIP} 已存在于主机清单中!',
    },
    'en': {
        'title': 'Flask Ansible Dashboard',
        'search': 'Search',
        'online': 'Online',
        'offline': 'Offline',
        'warming': 'Warming',
        'error': 'Error',
        'host_status': 'Host Status',
        'refresh': 'Refresh',
        'add' : 'Add',
        'logout' : 'Logout',
        'cpu_status': 'CPU Status',
        'service_status': 'Service Status',
        'memory_status' : 'Memory Status',
        'data_status' : 'Data Status',
        'memory' : 'Memory',
        'storage' : 'Storage',
        'contributors' : 'Contributors',
        'ip': 'IP Address',
        'GitHub_Repository' : 'GitHub Repository',
        'hostname' : 'HostName',
        'username' : 'UserName',
        'groupname' : 'GroupName',
        'password': 'Password',
        'port' : 'Port',
        'edit' : 'Edit',
        'delete' : 'Delete',
        'edit_message' : "Let's edit",
        'save' : 'Save',
        'input' : 'Input',
        'output' : 'Output',
        'deletc' : 'has been deleted',
        'delete_fail' : 'Deletion failed',
        'confirm_delete_host': 'Are you sure you want to delete host ID: {host_id}?',
        'edit_success' : 'Edit Successfully',
        'edit_fail' : 'Edition Fail',
        'check_network' : 'Request failed, please check the network',
        'checkip' : '{inputIP} has been in Hosts!',
    },
    'zh_HK': {
        'title': '綜合主機狀態監控大螢幕',
        'search': '搜尋主機名稱或IP...',
        'online': '線上',
        'offline': '離線',
        'warming': '警告',
        'error': '故障',
        'host_status': '主機狀態監控',
        'refresh': '刷新',
        'add' : '添加',
        'logout' : '登出',
        'cpu_status': 'CPU 利用率',
        'service_status': '服務狀態',
        'memory_status' : '內存使用',
        'data_status' : '數據流量',
        'memory' : '內存',
        'storage' : '磁碟',
        'contributors' : '貢獻者',
        'ip': 'IP 地址',
        'GitHub_Repository': 'GitHub 倉庫',
        'hostname' : '主機名',
        'username' : '用戶名',
        'groupname' : '群組名',
        'password': '密碼',
        'port' : '端口',
        'edit' : '编辑',
        'delete' : '删除',
        'edit_message' : '将编辑主机',
        'save' : '保存',
        'input' : '入口流量',
        'output' : '出口流量',
        'deletc' : '已刪除',
        'delete_fail' : '刪除失敗',
        'confirm_delete_host': '確定要刪除主機 ID: {host_id} 嗎？',
        'edit_success' : '編輯成功',
        'edit_fail' : '編輯失敗',
        'check_network' : '請求失敗，請檢查網絡',
        'checkip' : 'IP 位址 {inputIP} 已存在於主機清單中!',
    }
}
